# Generated by Django 5.2 on 2025-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_user_date_of_birth_user_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
