# Generated by Django 5.2 on 2025-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_userinteraction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
